const Countries = [
  'București',
  'Constanța',
  'Iași',
  'Timișoara',
  'Craiova',
  'Cluj-Napoca',
  'Galați',
  'Brașov',
  'Ploiești',
  'Brăila',
  'Bacău',
  'Oradea',
  'Arad',
  'Pitești',
  'Sibiu',
  'Târgu Mureș',
  'Baia Mare',
  'Buzău',
  'Satu Mare',
  'Botoșani',
  'Râmnicu Vâlcea',
  'Suceava',
  'Piatra Neamț',
  'Drobeta-Turnu Severin',
  'Focșani',
  'Târgu Jiu',
  'Tulcea',
  'Târgoviște',
  'Reșița',
  'Bistrița',
  'Slatina',
  'Călărași',
  'Hunedoara',
  'Vaslui',
  'Giurgiu',
  'Roman',
  'Deva',
  'Bârlad',
  'Alba Iulia',
  'Zalău',
  'Sfântu Gheorghe',
  'Turda',
  'Mediaș',
  'Slobozia',
  'Onești',
  'Alexandria',
  'Petroșani',
  'Lugoj',
  'Medgidia',
  'Pașcani',
  'Tecuci',
  'Miercurea Ciuc',
  'Sighetu Marmației',
  'Mangalia',
  'Râmnicu Sărat',
  'Câmpina',
  'Dej',
  'Câmpulung',
  'Odorheiu Secuiesc',
  'Reghin',
  'Mioveni',
  'Făgăraș',
  'Caracal',
  'Fetești',
  'Curtea de Argeș',
  'Năvodari',
  'Sighișoara',
  'Roșiorii de Vede',
  'Dorohoi',
  'Turnu Măgurele',
  'Fălticeni',
  'Huși',
  'Vulcan',
  'Rădăuți',
  'Oltenița',
  'Lupeni',
  'Caransebeș',
  'Cugir',
  'Săcele',
  'Câmpia Turzii',
  'Târnăveni',
  'Sebeș',
  'Aiud',
  'Petrila',
  'Borșa',
  'Zărnești',
  'Comănești',
  'Motru',
  'Carei',
  'Moinești',
  'Codlea',
  'Orăștie',
  'Gherla',
  'Balș',
  'Moreni',
  'Târgu Neamț',
  'Drăgășani',
  'Târgu Secuiesc',
  'Băilești',
  'Buhuși',
  'Corabia',
  'Câmpulung Moldovenesc',
  'Blaj',
  'Gheorgheni',
  'Calafat',
  'Adjud',
  'Cernavodă',
  'Băicoi',
  'Filiași',
  'Salonta',
  'Buftea',
  'Urziceni',
  'Bocșa',
  'Breaza',
  'Marghita',
  'Luduș',
  'Vișeu de Sus',
  'Brad',
  'Vatra Dornei',
  'Cisnădie',
  'Mizil',
  'Șimleu Silvaniei',
  'Toplița',
  'Zimnicea',
  'Gura Humorului',
  'Găești',
  'Pucioasa',
  'Negrești-Oaș',
  'Râșnov',
  'Avrig',
  'Baia Sprie',
  'Ocna Mureș',
  'Orșova',
  'Oravița',
  'Moldova Nouă',
  'Călan',
  'Sinaia',
  'Țăndărei',
  'Simeria',
  'Dărmănești',
  'Vicovu de Sus',
  'Târgu Ocna',
  'Târgu Lăpuș',
  'Vălenii de Munte',
  'Târgu Frumos',
  'Scornicești',
  'Comarnic',
  'Ovidiu',
  'Drăgănești-Olt',
  'Oțelu Roșu',
  'Mărășești',
  'Sânnicolau Mare',
  'Ianca',
  'Nehoiu',
  'Rovinari',
  'Strehaia',
  'Hațeg',
  'Videle',
  'Covasna',
  'Jibou',
  'Hârlău',
  'Sovata',
  'Uricani',
  'Agnita',
  'Costești',
  'Beiuș',
  'Beclean',
  'Darabani',
  'Bumbești-Jiu',
  'Urlați',
  'Măcin',
  'Bușteni',
  'Boldești-Scăeni',
  'Lipova',
  'Bolintin-Vale',
  'Năsăud',
  'Cristuru Secuiesc',
  'Hârșova',
  'Basarabi',
  'Dolhasca',
  'Victoria',
  'Babadag',
  'Aleșd',
  'Titu',
  'Sângeorz-Băi',
  'Valea lui Mihai',
  'Anina',
  'Otopeni',
  'Jimbolia',
  'Negrești',
  'Baraolt',
  'Ineu',
  'Topoloveni',
  'Tășnad',
  'Plopeni',
  'Siret',
  'Huedin',
  'Liteni',
  'Panciu',
  'Iernut',
  'Curtici',
  'Podu Iloaiei',
  'Budești',
  'Băbeni',
  'Ștei',
  'Seini',
  'Târgu Cărbunești',
  'Bălan',
  'Zlatna',
  'Roznov',
  'Tălmaciu',
  'Întorsura Buzăului',
  'Călimănești-Căciulata',
  'Bicaz',
  'Dumbrăveni',
  'Chișineu-Criș',
  'Salcea',
  'Segarcea',
  'Săveni',
  'Câmpeni',
  'Cehu Silvaniei',
  'Milișăuți',
  'Nădlac',
  'Dealu',
  'Buziaș',
  'Fieni',
  'Târgu Bujor',
  'Odobești',
  'Murgeni',
  'Pogoanele',
  'Brezoi',
  'Tismana',
  'Făget',
  'Însurăței',
  'Horezu',
  'Amara',
  'Pâncota',
  'Vlăhița',
  'Techirghiol',
  'Teiuș',
  'Cajvana',
  'Slănic',
  'Mihăilești',
  'Vânju Mare',
  'Deta',
  'Sebiș',
  'Abrud',
  'Predeal',
  'Lehliu Gară',
  'Broșteni',
  'Piatra Olt',
  'Frasin',
  'Geoagiu',
  'Rupea',
  'Fundulea',
  'Novaci',
  'Azuga',
  'Pietroșița',
  'Aninoasa',
  'Săliște',
  'Băile Herculane',
  'Bălcești',
  'Baia de Aramă',
  'Berbești',
  'Isaccea',
  'Băneasa',
  'Negru Vodă',
  'Cavnic',
  'Slănic Moldova',
  'Țicleni',
  'Copșa Mică',
  'Sulina',
  'Baia de Arieș',
  'Băile Olănești',
  'Solca',
  'Făurei',
  'Ocna Sibiului',
  'Berești',
  'Ocnele Mari',
  'Băile Govora',
  'Borsec',
  'Vașcău',
  'Nucet',
  'Băile Tușnad',
];

export default Countries;
